### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [Irina-prog/10sprint#1]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
В случае если вы затрудняетесь с составлением списка базовых правил можете воспользоваться сервисом-генератором, например gitignore.io

**Нужно исправить**: README файл должен содержать номер версии (ненулевой), ссылку на проект (github pages) и заголовок отражающий назначение проекта.

В дополнение к ссылкам из практики рекомендую почитать статью "Как написать хороший README?".

Ссылка на статью:
https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26
Примеры шаблонов для README:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию:
`some-extra-long-name@some.extra.long.domain.name` - доменное имя может содержать произвольное число поддоменов

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почы, содержащий несколько символов '-' подряд является 

### Номер телефона

Негативные:
**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
```
+9 2222222222
+7(925 900-90-90
+7925900-90-90
+792590090-90
+7(925) 9009090
+7(925)9009090
+7 925 900-90-90
```

### Адрес сайта
**Нужно исправить** следующие некорректные кейсы проходят валидацию

`http://www.ya.` - отсутствует доменная зона, точка на конце
`http://www` (отсутствует доменная зона)
`http://.ru` - отсутствует доменная имя
`http://127.` - некорректный IP, точка на конце
`http://127.0..`  - некорректный IP, точка на конце
`http://127.0.0..`  - некорректный IP, точка на конце
`https://mysite.23` - tld не может состоять только из цифр)

**Можно лучше** следующие некорректные кейсы проходят валидацию
`http://www.google.ru///////` - в пути количество слешей подряд должно быть ограничено 1

**Comment by Irina-prog** [comment]
Исправлено

**Comment by zlocate** [comment]
Пожалуйста не закрывайте Issue до окончания процесса ревью.

**Comment by zlocate** [comment]
Добрый вечер. Следующие кейсы требуют исправления:
### Email
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почы, содержащий несколько символов '-' подряд является 

### Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию

http://x.com:30 - доменное имя сайта может состоять из одной буквы и также номера порта

**Comment by zlocate** [comment]
Добрый вечер. К сожалению, после внесения последних правок следующие кейсы перестали обрабатываться корректно

### Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию
http://google.ru:98/ - адрес может содержать одиночный слеш на конце

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
x@gmail.com - имя ящика может состоять из одного символа

**Comment by zlocate** [comment]
Добрый день. Работа принята. Желаю успехов в дальнейшем прохождении курса
